name: Golang build v2

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

env:
  DOCKER_REPOSITORY: dbevernage/tourna
  DOCKER_IMAGE: aelm-workshop-23
  GOLANG_VERSION: 1.24.x

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ env.GOLANG_VERSION }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.GOLANG_VERSION }}

    - name: Build
      run: go build -o ../bin/workshop -v ./...
      working-directory: workshop-service
    - name: Upload /bin folder as artifact
      uses: actions/upload-artifact@v4
      with:
        name: workshop
        path: bin/
        retention-days: 1

  docker:
    # Dependency on previous step to complete
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: workshop
          path: ./bin
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      # Docker container steps
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}